# Generated by Django 5.2.13 on 2026-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0002_signal_macd_signal_rsi_signal_sma_200_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="analysis",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
