# Generated by Django 5.2.13 on 2026-04-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_signal_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='cmf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
