# Generated by Django 5.2 on 2026-04-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0004_signal_cmf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signal",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="signal",
            name="analysis",
            field=models.JSONField(
                default={}, help_text="Результат анализа: signal, score, reasons"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="signal",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="signal",
            name="signal_type",
            field=models.CharField(
                blank=True,
                choices=[("buy", "Buy"), ("sell", "Sell")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="source",
            field=models.CharField(
                default="tradingview",
                help_text="Источник сигнала (TradingView, MOEX, manual)",
                max_length=50,
            ),
        ),
    ]
