# Generated by Django 5.2 on 2026-04-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0005_alter_signal_options_alter_signal_analysis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signal",
            name="analysis",
            field=models.JSONField(
                default=dict, help_text="Результат анализа: signal, score, reasons"
            ),
        ),
    ]
